### ISSUE TITLE
Use Swift 5.2.5 in 5.2 docker because Codable fixes

### ISSUE THREAD

**Issue by ktoso** [apple/swift-cluster-membership#57]
We use top level encoders in tests and it would be nice to use the 5.2.5 swift in docker so we don't have to reintroduce the workarounds for 2.5.4.

CI is on 5.2.5 so that's good -- just about the 

`docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.53.yaml run test` to also pass.

5.3 is fine.

**Comment by tomerd** [comment]
the CI system will pull the latest 5.2 so that should work OOB?

**Comment by ktoso** [comment]
Ah I just realized what had happened.

I locally had a docker image from before 5.2.5 was released and it simply kept using that... Silly me, we're good here 👍
